name: CICD Reactjs Project

on: 
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 1. Go to your home directory
            cd /home/ubuntu
            
            # 2. Check if the repo folder exists, if not, clone it
            if [ ! -d "cicd_reactjs_demo" ]; then
              git clone https://github.com/rajprajapati2001/cicd_reactjs_demo.git
            fi
            
            # 3. Enter the folder
            cd cicd_reactjs_demo
            
            # 4. Pull latest changes, install, and build
            git pull origin main
            npm install
            npm run build