name: CICD Reactjs Project

on: 
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Load NVM into this session
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Use Node 22
            nvm use 22
            
            # Navigate to project
            cd /home/ubuntu/cicd_reactjs_demo
            
            # Update code
            git pull origin main
            
            # Clean install and build
            rm -rf node_modules
            npm install
            npm run build